"""Report models and AI Authorship Firewall schemas for Wharton-IC V2."""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AuthorshipType(str, Enum):
    HUMAN_AUTHORED = "HUMAN_AUTHORED"           # Genuinely written by student team members
    HUMAN_EDITED = "HUMAN_EDITED"               # Substantially revised/rewritten by students
    DETERMINISTIC_CODE = "DETERMINISTIC_CODE"   # Output from compiled numerical algorithms/tables
    SOURCE_QUOTATION = "SOURCE_QUOTATION"       # Direct cited excerpt from filings or case studies
    AI_GENERATED = "AI_GENERATED"               # Raw text generated by an LLM (Must NOT enter student report)
    AI_ASSISTED_IDEA = "AI_ASSISTED_IDEA"       # Idea brainstormed with AI, written by student with citation
    UNKNOWN = "UNKNOWN"                         # Unclassified text; blocked by firewall in production


class ContentBlock(BaseModel):
    """An individual paragraph, table, or figure in a report with strict authorship provenance."""
    block_id: str
    section_id: str
    authorship_type: AuthorshipType
    author_identity: str = Field(description="Student name, Python module name, or model identifier")
    content_text: str
    citations: List[str] = Field(default_factory=list)
    has_mandatory_disclosure: bool = False
    created_at: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))


class ReportEvidencePack(BaseModel):
    """Comprehensive compilation of verified evidence, tables, and decisions for student authors."""
    pack_id: str
    created_at: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    architecture_label: str = "TEAM CAPLET REPORT ARCHITECTURE (Awaiting Official Private Rubric)"
    
    verified_rules: List[Dict[str, Any]]
    client_mandate: Dict[str, Any]
    approved_strategy: Dict[str, Any]
    decision_timeline: List[Dict[str, Any]]
    trading_notes: str
    lessons_learned: List[Dict[str, Any]]
    
    # Quantitative & Evidence Tables (from deterministic calculations)
    research_proposals: List[Dict[str, Any]]
    evidence_claims_summary: Dict[str, Any]
    
    # Missing / Weak Lineage Alerts
    missing_evidence_alerts: List[str]
    unanswered_questions: List[str]
    contradictions_detected: List[str]
    
    ai_use_summary: Dict[str, Any]
