#!/usr/bin/env python3
"""Number trace for the Root-and-Branch working paper (RAB Kit, WS8).

AI-generated (Claude Code) for Team Caplet - not a competition submission.

Scans the paper's .tex files for \\nk{key} (a key in rab/numbers*.yaml) and \\src{path} (a results file relative to
the worktree root), fails if any key or file cannot be found, and writes trace_table.tex (Appendix C): one row per
key with its file, status and the quote_as string. Wildcards (e.g. reinvest.rung.*) expand to every matching key.
Run from anywhere: python rab/paper/make_trace.py
"""
from __future__ import annotations

import fnmatch
import re
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
RAB = HERE.parent
ROOT = RAB.parent
TEX = ["RAB_working_paper.tex", "appendix_cards.tex", "appendix_gates.tex"]
YAMLS = ["numbers.yaml", "numbers_ws2.yaml", "numbers_ws3.yaml", "numbers_ws4.yaml"]


def load_numbers() -> dict[str, tuple[str, dict]]:
    out: dict[str, tuple[str, dict]] = {}
    for name in YAMLS:
        doc = yaml.safe_load((RAB / name).read_text())
        for key, entry in (doc.get("numbers") or {}).items():
            if key in out:
                sys.exit(f"duplicate key across files: {key}")
            out[key] = (name, entry if isinstance(entry, dict) else {"value": entry})
    return out


def tex_escape(s: str) -> str:
    rep = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
           "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(rep.get(c, c) for c in s)


def main() -> int:
    text = "\n".join((HERE / t).read_text() for t in TEX)
    # ignore the macro definitions themselves
    keys = [k for k in re.findall(r"\\nk\{([^}]*)\}", text) if k not in ("#1", "...")]
    srcs = [s for s in re.findall(r"\\src\{([^}]*)\}", text) if s not in ("#1", "...")]
    numbers = load_numbers()

    missing: list[str] = []
    rows: list[str] = []
    seen: set[str] = set()
    for pattern in dict.fromkeys(keys):
        matches = sorted(k for k in numbers if fnmatch.fnmatchcase(k, pattern))
        if not matches:
            missing.append(f"key {pattern}")
            continue
        for k in matches:
            if k in seen:
                continue
            seen.add(k)
            fname, entry = numbers[k]
            q = str(entry.get("quote_as") or "")
            status = str(entry.get("status") or ("GATE B (stream file)" if fname != "numbers.yaml" else ""))
            kb = tex_escape(k).replace(".", r".\allowbreak{}").replace(r"\_", r"\_\allowbreak{}")
            rows.append(rf"\texttt{{{kb}}} & \texttt{{{tex_escape(fname)}}} & "
                        rf"{tex_escape(status[:60])} & {tex_escape(q)} \\")
    for s in dict.fromkeys(srcs):
        if not (ROOT / s).exists():
            missing.append(f"file {s}")

    if missing:
        print("TRACE FAIL:", *missing, sep="\n  ")
        return 1

    files = "\n".join(rf"\item \texttt{{{tex_escape(s)}}}" for s in dict.fromkeys(srcs))
    table = [
        r"\footnotesize",
        r"\begin{longtable}{>{\raggedright}p{4.2cm}>{\raggedright}p{2.2cm}>{\raggedright}p{2.4cm}>{\raggedright\arraybackslash}p{5.2cm}}",
        r"\toprule Key & File & Status & Quote as \\ \midrule \endhead",
        *rows,
        r"\bottomrule",
        r"\end{longtable}",
        r"\normalsize",
        r"\noindent Results files cited directly (each reproduced blind at Gate B, or a Gate C record):",
        r"\begin{itemize}", files, r"\end{itemize}",
        rf"\noindent {len(rows)} keys, {len(dict.fromkeys(srcs))} files; 0 missing.",
    ]
    (HERE / "trace_table.tex").write_text("% generated by make_trace.py - do not edit\n" + "\n".join(table) + "\n")
    print(f"TRACE OK: {len(rows)} keys ({len(dict.fromkeys(keys))} patterns), {len(dict.fromkeys(srcs))} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
