"""Build the two new Google Sheet tabs ("RAB Tickets", "RAB Notes") from the WS6 kit.

Inputs : rab/trades/tickets.csv, rab/trades/notes.csv (unchanged kit files)
Outputs: rab/sheets/rab_tickets.json / rab_notes.json  (2D arrays of values + formulas,
         written to the Sheet with the Sheets connector's update_formulas)
         rab/sheets/rab_tickets.csv / rab_notes.csv       (same grid, for a manual import)

Every derived number in the tabs is a formula over the ticket inputs; the kit's own
Preview total is kept beside the formula as a cross-check.
"""
import csv
import json
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
TRADES = HERE.parent / "trades"


def txt(v):
    """Cell text; blank for NaN; apostrophe-guard strings the Sheets parser would change."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    if isinstance(v, (int, float)):
        return v
    s = str(v)
    if s[:1] in "=+-" or s[:1].isdigit():
        return "'" + s
    return s


def num(v):
    if v is None or (isinstance(v, float) and pd.isna(v)) or v == "":
        return ""
    return float(v)


def tickets():
    t = pd.read_csv(TRADES / "tickets.csv")
    first = 10  # first data row (1-based)
    last = first + len(t) - 1
    rows = [
        ["RAB Tickets: Friday 2 Oct 2026 WInS orders (both books; the team's 1 Oct vote picks one)"]
        + [None] * 5,
        ["AI-generated by Claude Code (RAB Kit WS6) from rab/trades/tickets.csv. Nothing here places an order: "
         "students check and enter every order. Basis: 28 Sep 2026 closes; WInS bond prices from tab Book L. "
         "Friday: re-run refresh_tickets.py --basis friday and type the new prices into column K."] + [None] * 5,
        ["Inputs (official rules / WInS Notes)", "Value"],
        ["Starting WInS cash ($)", 300000],
        ["Commission per stock or ETF trade ($)", 25],
        ["Commission per Treasury trade ($)", 10],
        ["Never let cash fall below ($, kit stop rule 4)", 1000],
        ["Max trades allowed in the competition", 200],
    ]
    hdr = [
        "Book", "Order", "Ticker or bond", "Type", "Exact WInS name to look for", "Name status", "CUSIP",
        "Serves (Laura's plan)", "Quantity", "Quantity unit", "Reference price", "Price as of", "Price source",
        "Accrued interest per $100 (bonds)", "Max price (do not pay above)", "Commission ($)",
        "Expected cost incl. commission ($)", "Worst-case cost at max price ($)", "Kit Preview total ($, tickets.csv)",
        "Check: formula minus kit ($)", "Stop if Preview below ($)", "Stop if Preview above ($)",
        "Cash after: expected ($)", "Cash after: worst case ($)", "Cash check", "30-day avg daily volume",
        "Order size vs 2x daily volume", "Trap to avoid", "Alternate", "Why this order",
    ]
    rows.append(hdr)
    for i, r in enumerate(t.itertuples(index=False)):
        n = first + i
        bond = r.type == "Treasury"
        rows.append([
            txt(r.book), int(r.seq), txt(r.id), txt(r.type), txt(r.wins_name_expected), txt(r.wins_name_status),
            txt(r.cusip), txt(r.serves), int(r.qty), txt(r.qty_unit), num(r.ref_price), txt(r.ref_asof),
            txt(r.ref_source), num(r.accrued_trade) if bond else "", num(r.max_price),
            f'=IF(D{n}="Treasury",$B$6,$B$5)',
            f'=IF(D{n}="Treasury",I{n}/100*(K{n}+N{n}),I{n}*K{n})+P{n}',
            f'=IF(D{n}="Treasury",I{n}/100*(O{n}+N{n}),I{n}*O{n})+P{n}',
            num(r.preview_expected),
            f"=ROUND(Q{n}-S{n},2)",
            num(r.stop_if_preview_below), num(r.stop_if_preview_above),
            f"=$B$4-SUMIFS($Q${first}:Q{n},$A${first}:A{n},A{n})",
            f"=$B$4-SUMIFS($R${first}:R{n},$A${first}:A{n},A{n})",
            f'=IF(X{n}>=$B$7,"OK","STOP: below cash floor")',
            num(r.adv30),
            f'=IF(Z{n}="","bond: n/a",I{n}/(2*Z{n}))',
            txt(r.trap), txt(r.alternate), txt(r.why_here),
        ])
    end = len(rows)
    rows.append([None])
    rows.append(["Summary by book", "Trades", "Commissions ($)", "Expected spend ($)", "Cash left: expected ($)",
                 "Cash left: worst case ($)", "Share of the 200-trade limit"])
    for b in ["Portfolio", "BookL"]:
        rows.append([
            b,
            f'=COUNTIF($A${first}:$A${last},"{b}")',
            f'=SUMIFS($P${first}:$P${last},$A${first}:$A${last},"{b}")',
            f'=SUMIFS($Q${first}:$Q${last},$A${first}:$A${last},"{b}")',
            f'=$B$4-D{len(rows)+1}',
            f'=$B$4-SUMIFS($R${first}:$R${last},$A${first}:$A${last},"{b}")',
            f'=B{len(rows)+1}/$B$8',
        ])
    rows.append(["Portfolio: order 11 (VT) is placed the session after all five bonds show Filled (Mon 5 Oct ET), "
                 "sized from the cash WInS then shows (refresh_tickets.py --cash-before-vt)."])
    return rows, first, last


def notes():
    d = pd.read_csv(TRADES / "notes.csv")
    first = 5
    rows = [
        ["RAB Notes: one row per trade. Team note = what you paste into the WInS Trade note box (max 300 characters)."]
        + [None] * 5,
        ["The exemplar is an EXAMPLE only: the team rewrites every note in its own words before trading. "
         "Column M counts the Team note live; it turns red above 300. Rows marked 'conditional' are for a trade "
         "only if its condition happens (see 'When it is used')."] + [None] * 5,
        ["Trade note box limit (characters)", 300],
    ]
    rows.append([
        "Book", "Order", "Note ID", "Ticker or bond", "When it is used", "Laura goal", "TN Analysis role",
        "TN Analysis pick", "Brief (facts the note may use)", "Label", "Exemplar note", "Exemplar characters",
        "Team note (write here)", "Team note characters", "Characters left", "Team note status", "IPS lines it links to",
    ])
    for i, r in enumerate(d.itertuples(index=False)):
        n = first + i
        rows.append([
            txt(r.book), int(r.seq) if not pd.isna(r.seq) else "", txt(r.note_id), txt(r.ticker), txt(r.use),
            txt(r.role), txt(r.tn_role), txt(r.pick), txt(r.brief), txt(r.label), txt(r.exemplar),
            f"=LEN(K{n})", "", f"=LEN(M{n})", f"=$B$3-N{n}",
            f'=IF(N{n}=0,"empty",IF(N{n}>$B$3,"TOO LONG: cut "&(N{n}-$B$3)&" characters","OK"))',
            txt(r.ips_quote),
        ])
    return rows, first, first + len(d) - 1


def main():
    for name, (rows, first, last) in {"rab_tickets": tickets(), "rab_notes": notes()}.items():
        width = max(len(r) for r in rows)
        grid = [[(None if c is None else c) for c in r] + [None] * (width - len(r)) for r in rows]
        (HERE / f"{name}.json").write_text(json.dumps(grid, ensure_ascii=False))
        with open(HERE / f"{name}.csv", "w", newline="") as fh:
            w = csv.writer(fh)
            for r in grid:
                w.writerow(["" if c is None else c for c in r])
        print(name, "rows", len(grid), "cols", width, "data rows", first, "-", last)


if __name__ == "__main__":
    main()
