"""Phase C main-loop step: combine the three skeptics' verdicts per merged question and apply the four filters.

A merged question SURVIVES only if all hold (v4 Part 4, Phase C):
  1. so-what: a majority of skeptics say its answer would change a decision, number or sentence;
  2. anchor: a majority say it is genuinely tied to the official case/criteria or a verified fact;
  3. adversarial: at least 2 of 3 skeptics fail to kill it (kills < 2);
  4. simplicity: a majority say the insight fits one plain sentence.
If a skeptic call failed, the majority is taken over the verdicts available and the question is flagged.

Run from repo root: .venv/bin/python research/insight_v1/scripts/phase_C_survival.py JOURNAL [JOURNAL ...]
Writes research/insight_v1/phase_C/{survivors.json, parked.json, filter_log.md} and prints counts.
"""
import json
import sys
from collections import Counter, defaultdict

merged = {m["mid"]: m for m in json.load(open("research/insight_v1/phase_C/merged_questions.json"))}
votes = defaultdict(dict)
for j in sys.argv[1:]:
    rows = [json.loads(line) for line in open(j)]
    labels = {o.get("agentId"): o.get("label", "") for o in rows if o.get("type") == "started"}
    for o in rows:
        if o.get("type") != "result":
            continue
        r = o.get("result")
        # results are per-agent; the role is the first word of the agent's label (judge / answered / stats)
        if isinstance(r, dict) and "verdicts" in r:
            label = o.get("label") or labels.get(o.get("agentId"), "")
            role = label.split(" ")[0] if label else None
            for v in r["verdicts"]:
                votes[v["mid"]][role or f"anon{len(votes[v['mid']])}"] = v

surv, parked = [], []
reasons = Counter()
for mid, m in merged.items():
    vs = list(votes.get(mid, {}).values())
    n = len(vs)
    rec = dict(m)
    rec["skeptic_votes"] = votes.get(mid, {})
    rec["n_votes"] = n
    if n == 0:
        rec["filter_result"] = "NO_VOTES"
        parked.append(rec)
        reasons["no votes"] += 1
        continue
    maj = lambda key: sum(1 for v in vs if v.get(key)) * 2 > n  # noqa: E731
    kills = sum(1 for v in vs if v.get("kill"))
    ok = {"so_what": maj("so_what"), "anchor": maj("anchor_ok"), "simplicity": maj("simplicity_ok"),
          "adversarial": kills < 2 if n == 3 else kills * 2 < n}
    rec["filters"] = ok
    rec["kills"] = kills
    rec["priority"] = round(sum(v.get("priority", 0) for v in vs) / n, 2)
    rec["insight_guesses"] = [v.get("one_sentence_insight") for v in vs if v.get("one_sentence_insight")]
    rec["flag_incomplete_votes"] = n < 3
    if all(ok.values()):
        rec["filter_result"] = "SURVIVED"
        surv.append(rec)
    else:
        failed = [k for k, v in ok.items() if not v]
        rec["filter_result"] = "PARKED: failed " + ", ".join(failed)
        rec["kill_reasons"] = [f'{role}: {v.get("kill_reason")} - {v.get("evidence")}' for role, v in votes[mid].items() if v.get("kill")]
        for f in failed:
            reasons[f] += 1
        for v in vs:
            if v.get("kill"):
                reasons["kill:" + v.get("kill_reason", "?")] += 1
        parked.append(rec)

surv.sort(key=lambda r: -r["priority"])
json.dump(surv, open("research/insight_v1/phase_C/survivors.json", "w"), indent=1)
json.dump(parked, open("research/insight_v1/phase_C/parked.json", "w"), indent=1)
total_b = len(json.load(open("research/insight_v1/phase_B/questions.json")))
dedup = len(json.load(open("research/insight_v1/phase_C/questions_deduped.json")))
tags = Counter(r["domain_tag"] for r in surv)
tiers = Counter(d for r in surv for d in r["deliverables"])
log = f"""# Phase C filter log

Generated by `research/insight_v1/scripts/phase_C_survival.py` from the three skeptics' verdicts (roles: Wharton
semifinal reader; already-answered checker; statistician/wrong-premise hunter).

| Step | Count in | Dropped | Count out |
|---|---|---|---|
| Phase B questions (20 agents, 10 lenses) | {total_b} | | {total_b} |
| Exact duplicates (normalised text) | {total_b} | {total_b - dedup} | {dedup} |
| Structural screen (no anchor or no stated change) | {dedup} | 0 | {dedup} |
| Librarian: semantic duplicates merged into clusters | {dedup} | {dedup - len(merged)} merged away | {len(merged)} |
| Skeptic filters (so-what, anchor, 2-of-3 adversarial, simplicity) | {len(merged)} | {len(parked)} parked | {len(surv)} |

Why questions were parked (a question can fail several filters; kill reasons count each skeptic's kill):
{chr(10).join(f"- {k}: {v}" for k, v in reasons.most_common())}

Survivors by domain tag: {dict(tags)}
Survivors by deliverable they affect: {dict(tiers)}
Survivors with fewer than 3 votes (a skeptic call failed): {sum(1 for r in surv if r.get('flag_incomplete_votes'))}

Parked questions are listed in `parked.json` with each skeptic's reason. Scope is semifinals only, so they are not
turned into a Q&A bank.

## What this teaches
Most questions that sound important fail at least one plain test: would the answer change anything we submit, is it
tied to the case, has it already been answered, and can the insight be said in one sentence? Filtering hard before
researching is how a small team spends its time on the few questions that move the result.
"""
open("research/insight_v1/phase_C/filter_log.md", "w").write(log)
print(json.dumps({"merged": len(merged), "survived": len(surv), "parked": len(parked), "reasons": dict(reasons),
                  "by_tag": dict(tags), "votes_per_mid": dict(Counter(len(votes.get(m, {})) for m in merged))}, indent=1))
